###############################################################################
# Created by write_sdc
###############################################################################
current_design cpu_block
###############################################################################
# Timing Constraints
###############################################################################
create_clock -name clk -period 20.0000 [get_ports {clk}]
set_clock_transition 0.1500 [get_clocks {clk}]
set_clock_uncertainty 0.2500 clk
set_propagated_clock [get_clocks {clk}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_arready}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_arready}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_awready}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_awready}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_bvalid}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_bvalid}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_rdata[0]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_rdata[0]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_rdata[10]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_rdata[10]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_rdata[11]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_rdata[11]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_rdata[12]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_rdata[12]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_rdata[13]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_rdata[13]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_rdata[14]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_rdata[14]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_rdata[15]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_rdata[15]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_rdata[16]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_rdata[16]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_rdata[17]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_rdata[17]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_rdata[18]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_rdata[18]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_rdata[19]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_rdata[19]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_rdata[1]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_rdata[1]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_rdata[20]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_rdata[20]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_rdata[21]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_rdata[21]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_rdata[22]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_rdata[22]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_rdata[23]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_rdata[23]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_rdata[24]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_rdata[24]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_rdata[25]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_rdata[25]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_rdata[26]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_rdata[26]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_rdata[27]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_rdata[27]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_rdata[28]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_rdata[28]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_rdata[29]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_rdata[29]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_rdata[2]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_rdata[2]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_rdata[30]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_rdata[30]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_rdata[31]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_rdata[31]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_rdata[3]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_rdata[3]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_rdata[4]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_rdata[4]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_rdata[5]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_rdata[5]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_rdata[6]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_rdata[6]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_rdata[7]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_rdata[7]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_rdata[8]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_rdata[8]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_rdata[9]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_rdata[9]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_rvalid}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_rvalid}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_wready}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_wready}]
set_input_delay 0.2000 -clock [get_clocks {clk}] -min -add_delay [get_ports {resetn}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {resetn}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_araddr[0]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_araddr[0]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_araddr[10]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_araddr[10]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_araddr[11]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_araddr[11]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_araddr[12]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_araddr[12]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_araddr[13]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_araddr[13]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_araddr[14]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_araddr[14]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_araddr[15]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_araddr[15]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_araddr[16]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_araddr[16]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_araddr[17]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_araddr[17]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_araddr[18]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_araddr[18]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_araddr[19]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_araddr[19]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_araddr[1]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_araddr[1]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_araddr[20]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_araddr[20]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_araddr[21]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_araddr[21]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_araddr[22]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_araddr[22]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_araddr[23]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_araddr[23]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_araddr[24]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_araddr[24]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_araddr[25]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_araddr[25]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_araddr[26]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_araddr[26]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_araddr[27]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_araddr[27]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_araddr[28]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_araddr[28]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_araddr[29]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_araddr[29]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_araddr[2]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_araddr[2]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_araddr[30]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_araddr[30]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_araddr[31]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_araddr[31]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_araddr[3]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_araddr[3]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_araddr[4]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_araddr[4]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_araddr[5]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_araddr[5]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_araddr[6]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_araddr[6]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_araddr[7]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_araddr[7]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_araddr[8]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_araddr[8]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_araddr[9]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_araddr[9]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_arprot[0]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_arprot[0]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_arprot[1]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_arprot[1]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_arprot[2]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_arprot[2]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_arvalid}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_arvalid}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_awaddr[0]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_awaddr[0]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_awaddr[10]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_awaddr[10]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_awaddr[11]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_awaddr[11]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_awaddr[12]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_awaddr[12]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_awaddr[13]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_awaddr[13]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_awaddr[14]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_awaddr[14]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_awaddr[15]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_awaddr[15]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_awaddr[16]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_awaddr[16]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_awaddr[17]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_awaddr[17]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_awaddr[18]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_awaddr[18]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_awaddr[19]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_awaddr[19]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_awaddr[1]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_awaddr[1]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_awaddr[20]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_awaddr[20]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_awaddr[21]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_awaddr[21]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_awaddr[22]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_awaddr[22]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_awaddr[23]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_awaddr[23]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_awaddr[24]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_awaddr[24]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_awaddr[25]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_awaddr[25]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_awaddr[26]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_awaddr[26]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_awaddr[27]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_awaddr[27]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_awaddr[28]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_awaddr[28]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_awaddr[29]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_awaddr[29]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_awaddr[2]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_awaddr[2]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_awaddr[30]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_awaddr[30]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_awaddr[31]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_awaddr[31]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_awaddr[3]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_awaddr[3]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_awaddr[4]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_awaddr[4]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_awaddr[5]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_awaddr[5]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_awaddr[6]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_awaddr[6]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_awaddr[7]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_awaddr[7]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_awaddr[8]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_awaddr[8]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_awaddr[9]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_awaddr[9]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_awprot[0]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_awprot[0]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_awprot[1]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_awprot[1]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_awprot[2]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_awprot[2]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_awvalid}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_awvalid}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_bready}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_bready}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_rready}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_rready}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_wdata[0]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_wdata[0]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_wdata[10]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_wdata[10]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_wdata[11]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_wdata[11]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_wdata[12]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_wdata[12]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_wdata[13]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_wdata[13]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_wdata[14]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_wdata[14]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_wdata[15]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_wdata[15]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_wdata[16]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_wdata[16]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_wdata[17]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_wdata[17]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_wdata[18]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_wdata[18]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_wdata[19]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_wdata[19]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_wdata[1]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_wdata[1]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_wdata[20]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_wdata[20]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_wdata[21]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_wdata[21]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_wdata[22]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_wdata[22]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_wdata[23]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_wdata[23]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_wdata[24]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_wdata[24]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_wdata[25]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_wdata[25]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_wdata[26]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_wdata[26]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_wdata[27]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_wdata[27]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_wdata[28]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_wdata[28]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_wdata[29]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_wdata[29]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_wdata[2]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_wdata[2]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_wdata[30]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_wdata[30]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_wdata[31]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_wdata[31]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_wdata[3]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_wdata[3]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_wdata[4]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_wdata[4]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_wdata[5]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_wdata[5]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_wdata[6]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_wdata[6]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_wdata[7]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_wdata[7]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_wdata[8]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_wdata[8]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_wdata[9]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_wdata[9]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_wstrb[0]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_wstrb[0]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_wstrb[1]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_wstrb[1]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_wstrb[2]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_wstrb[2]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_wstrb[3]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_wstrb[3]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {mem_axi_wvalid}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {mem_axi_wvalid}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {trap}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {trap}]
###############################################################################
# Environment
###############################################################################
set_load -pin_load 0.0334 [get_ports {mem_axi_arvalid}]
set_load -pin_load 0.0334 [get_ports {mem_axi_awvalid}]
set_load -pin_load 0.0334 [get_ports {mem_axi_bready}]
set_load -pin_load 0.0334 [get_ports {mem_axi_rready}]
set_load -pin_load 0.0334 [get_ports {mem_axi_wvalid}]
set_load -pin_load 0.0334 [get_ports {trap}]
set_load -pin_load 0.0334 [get_ports {mem_axi_araddr[31]}]
set_load -pin_load 0.0334 [get_ports {mem_axi_araddr[30]}]
set_load -pin_load 0.0334 [get_ports {mem_axi_araddr[29]}]
set_load -pin_load 0.0334 [get_ports {mem_axi_araddr[28]}]
set_load -pin_load 0.0334 [get_ports {mem_axi_araddr[27]}]
set_load -pin_load 0.0334 [get_ports {mem_axi_araddr[26]}]
set_load -pin_load 0.0334 [get_ports {mem_axi_araddr[25]}]
set_load -pin_load 0.0334 [get_ports {mem_axi_araddr[24]}]
set_load -pin_load 0.0334 [get_ports {mem_axi_araddr[23]}]
set_load -pin_load 0.0334 [get_ports {mem_axi_araddr[22]}]
set_load -pin_load 0.0334 [get_ports {mem_axi_araddr[21]}]
set_load -pin_load 0.0334 [get_ports {mem_axi_araddr[20]}]
set_load -pin_load 0.0334 [get_ports {mem_axi_araddr[19]}]
set_load -pin_load 0.0334 [get_ports {mem_axi_araddr[18]}]
set_load -pin_load 0.0334 [get_ports {mem_axi_araddr[17]}]
set_load -pin_load 0.0334 [get_ports {mem_axi_araddr[16]}]
set_load -pin_load 0.0334 [get_ports {mem_axi_araddr[15]}]
set_load -pin_load 0.0334 [get_ports {mem_axi_araddr[14]}]
set_load -pin_load 0.0334 [get_ports {mem_axi_araddr[13]}]
set_load -pin_load 0.0334 [get_ports {mem_axi_araddr[12]}]
set_load -pin_load 0.0334 [get_ports {mem_axi_araddr[11]}]
set_load -pin_load 0.0334 [get_ports {mem_axi_araddr[10]}]
set_load -pin_load 0.0334 [get_ports {mem_axi_araddr[9]}]
set_load -pin_load 0.0334 [get_ports {mem_axi_araddr[8]}]
set_load -pin_load 0.0334 [get_ports {mem_axi_araddr[7]}]
set_load -pin_load 0.0334 [get_ports {mem_axi_araddr[6]}]
set_load -pin_load 0.0334 [get_ports {mem_axi_araddr[5]}]
set_load -pin_load 0.0334 [get_ports {mem_axi_araddr[4]}]
set_load -pin_load 0.0334 [get_ports {mem_axi_araddr[3]}]
set_load -pin_load 0.0334 [get_ports {mem_axi_araddr[2]}]
set_load -pin_load 0.0334 [get_ports {mem_axi_araddr[1]}]
set_load -pin_load 0.0334 [get_ports {mem_axi_araddr[0]}]
set_load -pin_load 0.0334 [get_ports {mem_axi_arprot[2]}]
set_load -pin_load 0.0334 [get_ports {mem_axi_arprot[1]}]
set_load -pin_load 0.0334 [get_ports {mem_axi_arprot[0]}]
set_load -pin_load 0.0334 [get_ports {mem_axi_awaddr[31]}]
set_load -pin_load 0.0334 [get_ports {mem_axi_awaddr[30]}]
set_load -pin_load 0.0334 [get_ports {mem_axi_awaddr[29]}]
set_load -pin_load 0.0334 [get_ports {mem_axi_awaddr[28]}]
set_load -pin_load 0.0334 [get_ports {mem_axi_awaddr[27]}]
set_load -pin_load 0.0334 [get_ports {mem_axi_awaddr[26]}]
set_load -pin_load 0.0334 [get_ports {mem_axi_awaddr[25]}]
set_load -pin_load 0.0334 [get_ports {mem_axi_awaddr[24]}]
set_load -pin_load 0.0334 [get_ports {mem_axi_awaddr[23]}]
set_load -pin_load 0.0334 [get_ports {mem_axi_awaddr[22]}]
set_load -pin_load 0.0334 [get_ports {mem_axi_awaddr[21]}]
set_load -pin_load 0.0334 [get_ports {mem_axi_awaddr[20]}]
set_load -pin_load 0.0334 [get_ports {mem_axi_awaddr[19]}]
set_load -pin_load 0.0334 [get_ports {mem_axi_awaddr[18]}]
set_load -pin_load 0.0334 [get_ports {mem_axi_awaddr[17]}]
set_load -pin_load 0.0334 [get_ports {mem_axi_awaddr[16]}]
set_load -pin_load 0.0334 [get_ports {mem_axi_awaddr[15]}]
set_load -pin_load 0.0334 [get_ports {mem_axi_awaddr[14]}]
set_load -pin_load 0.0334 [get_ports {mem_axi_awaddr[13]}]
set_load -pin_load 0.0334 [get_ports {mem_axi_awaddr[12]}]
set_load -pin_load 0.0334 [get_ports {mem_axi_awaddr[11]}]
set_load -pin_load 0.0334 [get_ports {mem_axi_awaddr[10]}]
set_load -pin_load 0.0334 [get_ports {mem_axi_awaddr[9]}]
set_load -pin_load 0.0334 [get_ports {mem_axi_awaddr[8]}]
set_load -pin_load 0.0334 [get_ports {mem_axi_awaddr[7]}]
set_load -pin_load 0.0334 [get_ports {mem_axi_awaddr[6]}]
set_load -pin_load 0.0334 [get_ports {mem_axi_awaddr[5]}]
set_load -pin_load 0.0334 [get_ports {mem_axi_awaddr[4]}]
set_load -pin_load 0.0334 [get_ports {mem_axi_awaddr[3]}]
set_load -pin_load 0.0334 [get_ports {mem_axi_awaddr[2]}]
set_load -pin_load 0.0334 [get_ports {mem_axi_awaddr[1]}]
set_load -pin_load 0.0334 [get_ports {mem_axi_awaddr[0]}]
set_load -pin_load 0.0334 [get_ports {mem_axi_awprot[2]}]
set_load -pin_load 0.0334 [get_ports {mem_axi_awprot[1]}]
set_load -pin_load 0.0334 [get_ports {mem_axi_awprot[0]}]
set_load -pin_load 0.0334 [get_ports {mem_axi_wdata[31]}]
set_load -pin_load 0.0334 [get_ports {mem_axi_wdata[30]}]
set_load -pin_load 0.0334 [get_ports {mem_axi_wdata[29]}]
set_load -pin_load 0.0334 [get_ports {mem_axi_wdata[28]}]
set_load -pin_load 0.0334 [get_ports {mem_axi_wdata[27]}]
set_load -pin_load 0.0334 [get_ports {mem_axi_wdata[26]}]
set_load -pin_load 0.0334 [get_ports {mem_axi_wdata[25]}]
set_load -pin_load 0.0334 [get_ports {mem_axi_wdata[24]}]
set_load -pin_load 0.0334 [get_ports {mem_axi_wdata[23]}]
set_load -pin_load 0.0334 [get_ports {mem_axi_wdata[22]}]
set_load -pin_load 0.0334 [get_ports {mem_axi_wdata[21]}]
set_load -pin_load 0.0334 [get_ports {mem_axi_wdata[20]}]
set_load -pin_load 0.0334 [get_ports {mem_axi_wdata[19]}]
set_load -pin_load 0.0334 [get_ports {mem_axi_wdata[18]}]
set_load -pin_load 0.0334 [get_ports {mem_axi_wdata[17]}]
set_load -pin_load 0.0334 [get_ports {mem_axi_wdata[16]}]
set_load -pin_load 0.0334 [get_ports {mem_axi_wdata[15]}]
set_load -pin_load 0.0334 [get_ports {mem_axi_wdata[14]}]
set_load -pin_load 0.0334 [get_ports {mem_axi_wdata[13]}]
set_load -pin_load 0.0334 [get_ports {mem_axi_wdata[12]}]
set_load -pin_load 0.0334 [get_ports {mem_axi_wdata[11]}]
set_load -pin_load 0.0334 [get_ports {mem_axi_wdata[10]}]
set_load -pin_load 0.0334 [get_ports {mem_axi_wdata[9]}]
set_load -pin_load 0.0334 [get_ports {mem_axi_wdata[8]}]
set_load -pin_load 0.0334 [get_ports {mem_axi_wdata[7]}]
set_load -pin_load 0.0334 [get_ports {mem_axi_wdata[6]}]
set_load -pin_load 0.0334 [get_ports {mem_axi_wdata[5]}]
set_load -pin_load 0.0334 [get_ports {mem_axi_wdata[4]}]
set_load -pin_load 0.0334 [get_ports {mem_axi_wdata[3]}]
set_load -pin_load 0.0334 [get_ports {mem_axi_wdata[2]}]
set_load -pin_load 0.0334 [get_ports {mem_axi_wdata[1]}]
set_load -pin_load 0.0334 [get_ports {mem_axi_wdata[0]}]
set_load -pin_load 0.0334 [get_ports {mem_axi_wstrb[3]}]
set_load -pin_load 0.0334 [get_ports {mem_axi_wstrb[2]}]
set_load -pin_load 0.0334 [get_ports {mem_axi_wstrb[1]}]
set_load -pin_load 0.0334 [get_ports {mem_axi_wstrb[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {clk}]
set_input_transition -min 0.1500 [get_ports {mem_axi_arready}]
set_input_transition -max 0.5000 [get_ports {mem_axi_arready}]
set_input_transition -min 0.1500 [get_ports {mem_axi_awready}]
set_input_transition -max 0.5000 [get_ports {mem_axi_awready}]
set_input_transition -min 0.1500 [get_ports {mem_axi_bvalid}]
set_input_transition -max 0.5000 [get_ports {mem_axi_bvalid}]
set_input_transition -min 0.1500 [get_ports {mem_axi_rvalid}]
set_input_transition -max 0.5000 [get_ports {mem_axi_rvalid}]
set_input_transition -min 0.1500 [get_ports {mem_axi_wready}]
set_input_transition -max 0.5000 [get_ports {mem_axi_wready}]
set_input_transition -min 0.1500 [get_ports {resetn}]
set_input_transition -max 0.5000 [get_ports {resetn}]
set_input_transition -min 0.1500 [get_ports {mem_axi_rdata[31]}]
set_input_transition -max 0.5000 [get_ports {mem_axi_rdata[31]}]
set_input_transition -min 0.1500 [get_ports {mem_axi_rdata[30]}]
set_input_transition -max 0.5000 [get_ports {mem_axi_rdata[30]}]
set_input_transition -min 0.1500 [get_ports {mem_axi_rdata[29]}]
set_input_transition -max 0.5000 [get_ports {mem_axi_rdata[29]}]
set_input_transition -min 0.1500 [get_ports {mem_axi_rdata[28]}]
set_input_transition -max 0.5000 [get_ports {mem_axi_rdata[28]}]
set_input_transition -min 0.1500 [get_ports {mem_axi_rdata[27]}]
set_input_transition -max 0.5000 [get_ports {mem_axi_rdata[27]}]
set_input_transition -min 0.1500 [get_ports {mem_axi_rdata[26]}]
set_input_transition -max 0.5000 [get_ports {mem_axi_rdata[26]}]
set_input_transition -min 0.1500 [get_ports {mem_axi_rdata[25]}]
set_input_transition -max 0.5000 [get_ports {mem_axi_rdata[25]}]
set_input_transition -min 0.1500 [get_ports {mem_axi_rdata[24]}]
set_input_transition -max 0.5000 [get_ports {mem_axi_rdata[24]}]
set_input_transition -min 0.1500 [get_ports {mem_axi_rdata[23]}]
set_input_transition -max 0.5000 [get_ports {mem_axi_rdata[23]}]
set_input_transition -min 0.1500 [get_ports {mem_axi_rdata[22]}]
set_input_transition -max 0.5000 [get_ports {mem_axi_rdata[22]}]
set_input_transition -min 0.1500 [get_ports {mem_axi_rdata[21]}]
set_input_transition -max 0.5000 [get_ports {mem_axi_rdata[21]}]
set_input_transition -min 0.1500 [get_ports {mem_axi_rdata[20]}]
set_input_transition -max 0.5000 [get_ports {mem_axi_rdata[20]}]
set_input_transition -min 0.1500 [get_ports {mem_axi_rdata[19]}]
set_input_transition -max 0.5000 [get_ports {mem_axi_rdata[19]}]
set_input_transition -min 0.1500 [get_ports {mem_axi_rdata[18]}]
set_input_transition -max 0.5000 [get_ports {mem_axi_rdata[18]}]
set_input_transition -min 0.1500 [get_ports {mem_axi_rdata[17]}]
set_input_transition -max 0.5000 [get_ports {mem_axi_rdata[17]}]
set_input_transition -min 0.1500 [get_ports {mem_axi_rdata[16]}]
set_input_transition -max 0.5000 [get_ports {mem_axi_rdata[16]}]
set_input_transition -min 0.1500 [get_ports {mem_axi_rdata[15]}]
set_input_transition -max 0.5000 [get_ports {mem_axi_rdata[15]}]
set_input_transition -min 0.1500 [get_ports {mem_axi_rdata[14]}]
set_input_transition -max 0.5000 [get_ports {mem_axi_rdata[14]}]
set_input_transition -min 0.1500 [get_ports {mem_axi_rdata[13]}]
set_input_transition -max 0.5000 [get_ports {mem_axi_rdata[13]}]
set_input_transition -min 0.1500 [get_ports {mem_axi_rdata[12]}]
set_input_transition -max 0.5000 [get_ports {mem_axi_rdata[12]}]
set_input_transition -min 0.1500 [get_ports {mem_axi_rdata[11]}]
set_input_transition -max 0.5000 [get_ports {mem_axi_rdata[11]}]
set_input_transition -min 0.1500 [get_ports {mem_axi_rdata[10]}]
set_input_transition -max 0.5000 [get_ports {mem_axi_rdata[10]}]
set_input_transition -min 0.1500 [get_ports {mem_axi_rdata[9]}]
set_input_transition -max 0.5000 [get_ports {mem_axi_rdata[9]}]
set_input_transition -min 0.1500 [get_ports {mem_axi_rdata[8]}]
set_input_transition -max 0.5000 [get_ports {mem_axi_rdata[8]}]
set_input_transition -min 0.1500 [get_ports {mem_axi_rdata[7]}]
set_input_transition -max 0.5000 [get_ports {mem_axi_rdata[7]}]
set_input_transition -min 0.1500 [get_ports {mem_axi_rdata[6]}]
set_input_transition -max 0.5000 [get_ports {mem_axi_rdata[6]}]
set_input_transition -min 0.1500 [get_ports {mem_axi_rdata[5]}]
set_input_transition -max 0.5000 [get_ports {mem_axi_rdata[5]}]
set_input_transition -min 0.1500 [get_ports {mem_axi_rdata[4]}]
set_input_transition -max 0.5000 [get_ports {mem_axi_rdata[4]}]
set_input_transition -min 0.1500 [get_ports {mem_axi_rdata[3]}]
set_input_transition -max 0.5000 [get_ports {mem_axi_rdata[3]}]
set_input_transition -min 0.1500 [get_ports {mem_axi_rdata[2]}]
set_input_transition -max 0.5000 [get_ports {mem_axi_rdata[2]}]
set_input_transition -min 0.1500 [get_ports {mem_axi_rdata[1]}]
set_input_transition -max 0.5000 [get_ports {mem_axi_rdata[1]}]
set_input_transition -min 0.1500 [get_ports {mem_axi_rdata[0]}]
set_input_transition -max 0.5000 [get_ports {mem_axi_rdata[0]}]
###############################################################################
# Design Rules
###############################################################################
set_max_transition 1.5000 [current_design]
set_max_capacitance 0.2000 [current_design]
set_max_fanout 16.0000 [current_design]
