###############################################################################
# PicoRV32 AXI CPU Block
# V3 Hierarchical Physical Design
# 50 MHz = 20 ns
###############################################################################

current_design cpu_block

# ----------------------------------------------------------------------
# Clock
# ----------------------------------------------------------------------

create_clock \
    -name clk \
    -period 20.000 \
    [get_ports {clk}]

set_clock_transition 0.150 [get_clocks {clk}]
set_clock_uncertainty 0.250 [get_clocks {clk}]

if {
    [info exists ::env(OPENLANE_SDC_IDEAL_CLOCKS)] &&
    $::env(OPENLANE_SDC_IDEAL_CLOCKS)
} {
    unset_propagated_clock [get_clocks {clk}]
} else {
    set_propagated_clock [get_clocks {clk}]
}


# ----------------------------------------------------------------------
# AXI INPUTS TO CPU BLOCK
#
# Initial hierarchical timing budget:
# external TOP logic gets 4 ns before data reaches CPU macro input.
# ----------------------------------------------------------------------

set axi_inputs [get_ports {
    mem_axi_awready
    mem_axi_wready
    mem_axi_bvalid
    mem_axi_arready
    mem_axi_rvalid
    mem_axi_rdata*
}]

set_input_delay \
    -min 0.000 \
    -clock [get_clocks {clk}] \
    $axi_inputs

set_input_delay \
    -max 4.000 \
    -clock [get_clocks {clk}] \
    $axi_inputs

set_input_transition \
    -min 0.150 \
    $axi_inputs

set_input_transition \
    -max 0.500 \
    $axi_inputs


# ----------------------------------------------------------------------
# AXI OUTPUTS FROM CPU BLOCK
#
# Reserve 4 ns after CPU macro output for:
# top routing + AXI interconnect + destination logic/macro.
# ----------------------------------------------------------------------

set cpu_outputs [get_ports {
    trap
    mem_axi_awvalid
    mem_axi_awaddr*
    mem_axi_awprot*
    mem_axi_wvalid
    mem_axi_wdata*
    mem_axi_wstrb*
    mem_axi_bready
    mem_axi_arvalid
    mem_axi_araddr*
    mem_axi_arprot*
    mem_axi_rready
}]

set_output_delay \
    -min 0.000 \
    -clock [get_clocks {clk}] \
    $cpu_outputs

set_output_delay \
    -max 4.000 \
    -clock [get_clocks {clk}] \
    $cpu_outputs

# Initial macro boundary load model.
# Same load magnitude used in the V2 balanced SoC constraint.
set_load -pin_load 0.0334 $cpu_outputs


# ----------------------------------------------------------------------
# Reset
#
# resetn is generated by the top-level reset synchronizer and is
# deasserted synchronously to clk.
#
# Therefore resetn -> internal sequential paths MUST be timed.
#
# Reserve 4 ns at the hierarchical boundary for:
# top reset-sync FF clock-to-Q + top routing to CPU macro pin.
# ----------------------------------------------------------------------

set_input_delay \
    -min 0.200 \
    -clock [get_clocks {clk}] \
    [get_ports {resetn}]

set_input_delay \
    -max 4.000 \
    -clock [get_clocks {clk}] \
    [get_ports {resetn}]

set_input_transition \
    -min 0.150 \
    [get_ports {resetn}]

set_input_transition \
    -max 0.500 \
    [get_ports {resetn}]


# ----------------------------------------------------------------------
# Clock source model
# ----------------------------------------------------------------------

set_driving_cell \
    -lib_cell sky130_fd_sc_hd__inv_2 \
    -pin Y \
    [get_ports {clk}]


# ----------------------------------------------------------------------
# Electrical constraints
# ----------------------------------------------------------------------

set_max_transition 1.500 [current_design]
set_max_capacitance 0.200 [current_design]
set_max_fanout 16 [current_design]
